### PR TITLE
docs: add user-guide for scheduling gates queue admission

### PR DESCRIPTION
**Pull request by devzizu**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

/kind documentation

**What this PR does / why we need it**:

This PR introduces user-facing documentation for the feature introduced in https://github.com/volcano-sh/volcano/pull/5033.

**Which issue(s) this PR fixes**:

https://github.com/volcano-sh/website/issues/494

### CODE REVIEW

File: content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+# empty output
+```
+
+## Interaction with other Scheduling Gates
+
+If a pod has additional scheduling gates from other controllers (e.g., `example.com/my-gate`), Volcano will not remove its gate until the pod has **only the Volcano gate remaining**. This ensures Volcano does not interfere with other gate controllers.
+
+## Limitations
+
+- Once a pod's gate is removed, it reserves queue capacity until it is scheduled or deleted. If the pod remains unschedulable (*e.g.*, waiting for the autoscaler to add nodes), it continues to hold queue capacity, potentially blocking other pods. Additionally, the feature currently **does not implement a timeout** for reserved capacity. Operators should be aware that *ungated-but-unschedulable* pods can hold queue capacity indefinitely.
```
[the remark this answers is not in the document]
Comment (devzizu) [reply content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md]: Fixed!

File: content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+Once the queue has capacity and the scheduler removes the gate, the field will be empty:
+
+```bash
+kubectl get pod my-pod -o jsonpath='{.spec.schedulingGates}'
+# empty output
+```
+
+## Interaction with other Scheduling Gates
+
+If a pod has additional scheduling gates from other controllers (e.g., `example.com/my-gate`), Volcano will not remove its gate until the pod has **only the Volcano gate remaining**. This ensures Volcano does not interfere with other gate controllers.
```
[the remark this answers is not in the document]
Comment (devzizu) [reply content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md]: Fixed!

File: content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+
+## Problem
+
+Volcano marks pods as `Unschedulable` for any allocation failure, whether it's due to insufficient cluster resources (where autoscaling is appropriate) or queue capacity limits (where autoscaling is not needed). Cluster autoscalers cannot distinguish between these scenarios, causing unnecessary node scale-ups. 
+
+The problem is described in detail in the [design document](https://github.com/volcano-sh/volcano/blob/master/docs/design/scheduling-gates-queue-admission.md).
+
+## Solution
+
+This feature uses Kubernetes [`schedulingGates`](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) to hold pods until the queue has capacity and while gated, pods are invisible to autoscalers. The gate is removed only after the queue capacity check passes, meaning, if the pod then can't schedule due to missing nodes, it gets marked `Unschedulable` legitimately, and autoscalers can respond correctly.
```
[the remark this answers is not in the document]
Comment (devzizu) [reply content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md]: Fixed!

File: content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md [hunk 4]
```diff
@@ -0,0 +1,142 @@
++++
```
[the remark this answers is not in the document]
Comment (devzizu) [reply content/en/docs/user_guide_how_to_use_scheduling_gates_queue_admission.md:1]: No, Gemini is wrong here. All existing guides (e.g., `user_guide_how_to_use_capacity_plugin.md`) live flat in `content/en/docs/` with the `user_guide_` prefix. There is no `user-guide/` subdirectory, so this comment may be dismissed.

**Comment by JesseStutler** [comment]
/approve
/lgtm
Thank you so much! ❤️
